theme: jekyll-theme-minimal
layout: default
show_downloads: true
github:
  zip_url: https://github.com/knvsl/teapot-demo/archive/master.zip
  tar_url: https://github.com/knvsl/teapot-demo/archive/master.tar.gz
